# Generated by Django 4.2 on 2023-04-24 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='аggregation',
            field=models.CharField(max_length=500, verbose_name='Агрегатирование'),
        ),
    ]
