# Generated by Django 4.2 on 2023-05-03 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('example_app', '0002_alter_product_аggregation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата сделки')),
                ('quantity', models.IntegerField(verbose_name='Количество проданного товара, шт.')),
                ('delivery_price', models.IntegerField(max_length=20, verbose_name='Цена ед. товара, руб.')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='example_app.product', verbose_name='Товар')),
            ],
        ),
    ]
